statusanyuk/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "statusan-yuk"

urlpatterns = [
    url(r'^$', views.statusan , name="statusan"),
    path('tambah-status/<str:nama>/<str:status>', views.tambah_status, name="tambah_status"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.signup, name='signup'),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statusanyuk.urls')),
    path('register/', user_views.signup, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('profile/', user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

statusanyuk/models.py
from django.db import models

# Create your models here.
class Statusan(models.Model):
    nama = models.CharField(max_length=40, null=True, blank=True)
    status = models.TextField()
    tanggal_buat = models.DateTimeField(auto_now_add=True)
    warna = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.nama

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    fullname = models.CharField(max_length=100, null=True)
    date_birth = models.DateField(null=True)
    # image = models.ImageField(default='default.jpeg', upload_to='profile_pics')
    image = models.URLField(max_length=1000, null=True)
    def __str__(self):
        return f'{self.user.username} Profile'

statusanyuk/forms.py
from django import forms

class Statusan_Form(forms.Form):
    nama_attrs = {
        'type': 'text',
        'class': 'form-control mb-4',
        'placeholder': 'Masukkan nama...'
    }
    status_attrs = {
        'type':'text',
        'class':'form-control',
        'placeholder':'Masukkan statusmu...'
    }

    nama = forms.CharField(label='', required=None,max_length=27, widget=forms.TextInput(attrs=nama_attrs))
    status = forms.CharField(label='', required=True,max_length=1000, widget=forms.Textarea(attrs=status_attrs))

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    # email = form.emailField()
    class Meta:
        model = User
        fields = ['username','password1', 'password2']

statusanyuk/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,HttpResponseRedirect
from .forms import Statusan_Form
from .models import Statusan
import time
from django.utils import timezone
import random
from itertools import cycle

response={}

# Untuk Challenge mengganti warna box dimana warna 
# berikut akan dipassing sebagai warna pada class Bootstrap 4 di statusan.html
warna_list = ['success','info', 'warning', 'danger', 'secondary', 'primary','dark']
warna_cycle = cycle(warna_list)



def statusan(request):

    if not request.user.is_authenticated:
        return redirect('login/')
    # Membuat session expired dalam 300 detik (5 menit)
    request.session.set_expiry(300)

    response['status'] = Statusan.objects.all()
    response['status_form'] = Statusan_Form

    # Jika button ditekan warna akan terganti
    if(request.POST.get('color', False)):
        id = request.POST.get('color', False)
        obj = Statusan.objects.get(id=id)
        obj.warna = next(warna_cycle)
        obj.save()


    form = Statusan_Form(request.POST or None)
    # Jika form diisikan secara valid
    if(request.method == 'POST' and form.is_valid()):
        response['nama'] = request.POST['nama']
        response['status'] = request.POST['status']
        # Jika nama yang diisikan kosong
        if(response['nama'] == ''):
            response['nama'] = 'Anonim'
        return render(request, 'confirmation.html', response)
        
    return render(request, "statusan.html", response)
def tambah_status(request, nama, status):
    
    statusan = Statusan(nama=nama, status=status, warna=random.choice(warna_list))
    statusan.save()
    return redirect('statusan-yuk:statusan')
    

user/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User


# Create your views here.
def signup(request):
    
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            form = form.cleaned_data.get('username')
            messages.success(request, f'Selamat Anda sudah berhasil membuat akun!')
            return redirect('login')
        

    else:
        form = UserRegisterForm()


    return render(request, 'signup.html', {'form':form})

@login_required
def profile(request):
    try:
        pengguna = Profile.objects.get(user__username= request.user.username)
    except:
        pengguna = Profile.objects.filter(user__username= request.user.username)
    return render(request, 'profile.html', {'pengguna':pengguna})

statusanyuk/templates/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StatusanYuk</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">StatusanYuk</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link disabled" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link disabled" href="{% url 'logout' %}">Log out</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'register' %}" >Register</a>
                <a class="nav-item nav-link" href="{% url 'login' %}">Log in</a>
            {% endif %}
          </div>
        </div>
      </nav>


    {% block content %}
    {% endblock %}

</body>
</html>

statusanyuk/templates/confirmation.html
{% extends 'base.html' %}

{% block content %}

<h1 style=" margin-bottom: 8%">U sure?</h1>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-3">
        <div class="card text-white bg-dark mb-3">
            <div class="card-body p-1">
                <p class="card-text text-center">{{nama}}</p>
            </div>
        </div>
    </div>

    <div class="col-lg-9 col-md-9 col-sm-9 col-9">
        <div class="card text-white bg-dark mb-3">
            <div class="card-body p-2">                            
            <p class="card-text">{{status}}</p>
            </div>
    </div>
    </div>
</div>

<form action="{% url 'statusan-yuk:tambah_status' nama status  %}" method="POST">
    {% csrf_token %}
    <input id="button-yes" type="submit" name="btn" value="yes" class='btn btn-success'>
    <a href="{% url 'statusan-yuk:statusan' %}" id="cancel" name="cancel" class="btn btn-danger">cancel</a>
</form>
    

{% endblock %}

statusanyuk/templates/statusan.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
<section id="section-judul">
<h1 id="header_title" style="font-family: 'Dancing Script', cursive; font-size:5rem; text-align: center; margin-bottom: 8%;">StatusanYuk</h1>
</section>


{% if user.is_authenticated %}
    <p style="color: green; font-size: x-large; text-align: center;">Hi, selamat datang {{ user.username }}.</p>
{% endif %}


<section name="status-list">
    <div class="container">
        <div class="row">
            {% if status %}
                {% for isi in status %}
                    <div class="col-lg-2 col-md-2 col-sm-2 col-2">
                        <div class="card text-white bg-{{isi.warna}} mb-3">
                            <div class="card-body p-1">
                                <p class="card-text text-center">{{isi.nama}}</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-9 col-md-9 col-sm-9 col-9">
                        <div class="card text-white bg-{{isi.warna}} mb-3">
                            
                            <div class="card-body p-2">                            
                            <p class="card-text">{{isi.status}}</p>
                            <p class="text-right font-weight-light">{{isi.tanggal_buat}}</p>
                            </div>
                    </div>
                    </div class="col-lg-1 col-md-1 col-sm-1 col-1">
                        <form action="{% url 'statusan-yuk:statusan' %}" method="POST" >
                            {% csrf_token %}
                            <button value="{{isi.id}}" name="color" >Color</button>
                        </form>
                    <div>

                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Yaw!</strong> Gada yang update nihh...
            </div>
            {% endif %}
        
    </div>

</section>

<section name="input-status" id="input-status">
    <div class="container">
        
        <form id="form" method="POST" action="{% url 'statusan-yuk:statusan'  %}">
            <h1>Update Statusmu</h1>
            {% csrf_token %}
            <div class="form-group">
            {{status_form.nama}}
            {{status_form.status }}
            </div>
            <div class="form-group row">
              <div class="col-sm-10">
                <button type="submit" id="submit" class="btn btn-primary" value="Submit">Submit</button>
              </div>
            </div>
        
            
          </form>
    </div>


</section>




{% endblock %}

user/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <link rel="stylesheet" href="{% static 'user.css' %}" type="text/css">

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
        {{message}}
    </div>
    {% endfor %}
    {% endif %}

    <div class="signup-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class='border-bottom mb-4'>Yuk Log In</legend>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info">Login</button>
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Belom punya akun? <a class='ml-2' href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>

    </div>
    
{% endblock %}

user/templates/logout.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    
    <h2>Anda telah log out</h2>
    <div class="signup-section">

        <div class="border-top pt-3">
            <small class="text-muted">
                <a class='ml-2' href="{% url 'login' %}">Login Lagi</a>
            </small>
        </div>

    </div>
    
{% endblock %}

user/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% load staticfiles %}
<!-- {{ user.profile.image.url }} -->
    <div class="content-section">
      <div class="media"> 
        <img class="rounded-circle account-img rounded img-fluid" style="width: 30%;height: auto;" src="{{ pengguna.image }}">
        <div class="media-body">
          <h2 class="account-heading" style="text-align: center;">fullname : {{ pengguna.fullname }}</h2>
          <h2 class="account-heading" style="text-align: center;">date birth : {{ pengguna.date_birth }}</h2>
          <!-- <p class="text-secondary">{{ pengguna.email }}</p> -->
        </div>
      </div>
      
    </div>
{% endblock %}

user/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="signup-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class='border-bottom mb-4'>Gabung sekarang</legend>
                {{form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info">Sign Up</button>
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Udah punya akun? <a class='ml-2' href="{% url 'login' %}">Sign In</a>
            </small>
        </div>

    </div>
    
{% endblock %}